---


# ==============================================================================
#                        Preparation Configure OS Common
# ==============================================================================

kubeadm_temp_folder: "/root/download"