---

# ==============================================================================
#                                      Harbor
# ==============================================================================

harbor_repository_name: "harbor.fillswim.local"
harbor_repository_http_method: "https"