---

# ============================================== Ping ==============================================

- name: Ping
  become: true
  ansible.builtin.ping:

# ====================================== Edit /etc/crictl.yaml =====================================

- name: Copy /etc/crictl.yaml
  become: true
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart containerd
