# ==============================================================================
#                                SSH Settings
# ==============================================================================

ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: auto_silent

# ==============================================================================
#                                  Image Repository
# ==============================================================================

# Docker Proxy Registry Type
docker_proxy_registry_type: "nexus"
# docker_proxy_registry_type: "harbor"

# nexus-lxc.fillswim.local (HTTPS)
image_repository_name: "nexus-lxc.fillswim.local"
image_repository_http_method: "https"

# # nexus.fillswim.local (HTTP)
# image_repository_name: "nexus.fillswim.local"
# image_repository_http_method: "http"

# # harbor.fillswim.local (HTTPS)
# image_repository_name: "harbor.fillswim.local"
# image_repository_http_method: "https"

# ==============================================================================
#                                Install ContainerD
# ==============================================================================

install_containerd: false
# containerd_version: "2.3.0"

# ==============================================================================
#                                Install NerdCTL
# ==============================================================================

install_nerdctl: false
# nerdctl_version: "2.2.2"

# ==============================================================================
#                                Install CRI-O
# ==============================================================================

# Kubernetes
kubernetes_major_version: "1.35"
kubernetes_minor_version: "1.35.3"

install_crio: true