---

# https://nexus-lxc.fillswim.local:8443/repository/raw-hosted/nerdctl/v2.2.2/nerdctl-2.2.2-linux-amd64.tar.gz
file_path: "nerdctl/v{{ nerdctl_version }}/nerdctl-{{ nerdctl_version }}-linux-amd64.tar.gz"
nerdctl_url: "{{ nexus_raw_hosted_repository_url }}/{{ file_path }}"
