---
# tasks file for 03-Install-1st-Master-Node

# - name: Ping
#   become: true
#   ansible.builtin.ping:

# =============================================================================
#                        Проверка, что кластер уже создан
# =============================================================================

- name: Проверка, что кластер уже создан
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Конец playbook
  ansible.builtin.meta: end_play
  when: kubeadm_ca.stat.exists

# =============================================================================
#                                Kubeadm Init
# =============================================================================

- name: Создание папки /root/kubeadm
  ansible.builtin.file:
    path: /root/kubeadm
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Скопировать kubeadm-config.yaml (v1beta3)
  become: true
  when: kubeadm_api_version == "v1beta3"
  ansible.builtin.template:
    src: kubeadm-config-v3.yaml.j2
    dest: /root/kubeadm/kubeadm-config.yaml
    owner: root
    group: root
    mode: "0644"

- name: Скопировать kubeadm-config.yaml (v1beta4)
  become: true
  when: kubeadm_api_version == "v1beta4"
  ansible.builtin.template:
    src: kubeadm-config-v4.yaml.j2
    dest: /root/kubeadm/kubeadm-config.yaml
    owner: root
    group: root
    mode: "0644"

- name: Kubeadm Init с kube-proxy
  when:
    - not ciliun_enabled
  ansible.builtin.shell: |
    set -o pipefail
    kubeadm init \
    --config /root/kubeadm/kubeadm-config.yaml
  register: kubeadm_init_result
  args:
    executable: /bin/bash
  notify:
    - Restart kubelet

- name: Kubeadm Init без kube-proxy (для Cilium)
  when:
    - ciliun_enabled
  ansible.builtin.shell: |
    set -o pipefail
    kubeadm init \
    --config /root/kubeadm/kubeadm-config.yaml \
    --skip-phases=addon/kube-proxy
  register: kubeadm_init_result
  args:
    executable: /bin/bash
  notify:
    - Restart kubelet

- name: Вывод результатов работы Kubeadm Init
  ansible.builtin.debug:
    var: kubeadm_init_result.stdout

- name: Создание папки /root/.kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: "0775"

- name: Скопировать /etc/kubernetes/admin.conf в /root/.kube/config
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    owner: root
    group: root
    mode: "0600"

# =============================================================================
#                              Перезагрузка сервера
# =============================================================================

- name: Перезагрузка сервера
  throttle: 1
  become: true
  ansible.builtin.reboot:
