---

- name: Adding-Other-Control-Nodes
  serial: 1                           # Выполнять роль будет одновременно только на одной ноде от и до
  order: inventory                    # Ноды будут выбираться в порядке, как в inventory
  hosts: all

  roles:
    - role: 04-Adding-Other-Nodes
