---
k8s1_alma_vm:
  children:
    k8s_masters:
    k8s_workers:

# Control nodes
k8s_masters:
  hosts:
    k8s1-alma-vm-master-1.fillswim.local:
      ansible_host: 192.168.2.111
    k8s1-alma-vm-master-2.fillswim.local:
      ansible_host: 192.168.2.112
    k8s1-alma-vm-master-3.fillswim.local:
      ansible_host: 192.168.2.113

# Worker nodes
k8s_workers:
  hosts:
    k8s1-alma-vm-worker-1.fillswim.local:
      ansible_host: 192.168.2.114
    k8s1-alma-vm-worker-2.fillswim.local:
      ansible_host: 192.168.2.115
    k8s1-alma-vm-worker-3.fillswim.local:
      ansible_host: 192.168.2.116
