# Control nodes
k8s_masters:
  hosts:
    k8s1-redos-cpl01.fillswim.local:
      ansible_host: 192.168.2.111
    k8s1-redos-cpl02.fillswim.local:
      ansible_host: 192.168.2.112
    k8s1-redos-cpl03.fillswim.local:
      ansible_host: 192.168.2.113

# Worker nodes
k8s_workers:
  hosts:
    k8s1-redos-app01.fillswim.local:
      ansible_host: 192.168.2.114
    k8s1-redos-app02.fillswim.local:
      ansible_host: 192.168.2.115

k8s1_redos_cluster:
  children:
    k8s_masters:
    k8s_workers:
