---
# tasks file for Containerd-config

- name: Скопировать config.toml
  become: true
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart containerd
