---

- name: Блок проверки функционирования Longhorn
  delegate_to: "{{ first_cpl_node }}"
  run_once: true
  block:

    # ======================================================================

    - name: Подсчет в цикле количества подов Longhorn в состоянии не Running
      changed_when: false
      ignore_errors: true
      ansible.builtin.shell: |
        kubectl get pods -n longhorn-system --no-headers | grep -iv Running | wc -l
      register: count_longhorn_pods_not_running
      until: count_longhorn_pods_not_running.stdout == target_count
      retries: 120    # 10 минут максимум
      delay: 5        # с задержкой в 5 секунду

    - name: Вывод количества подов Longhorn в состоянии не Running
      ansible.builtin.debug:
        var: count_longhorn_pods_not_running.stdout

    - name: Вывод сообщения о количестве подов Longhorn в состоянии Running
      ignore_errors: true
      ansible.builtin.assert:
        that: count_longhorn_pods_not_running.stdout|regex_search("{{ target_count }}")
        fail_msg: "Не все поды Longhorn в состоянии Running"
        success_msg: "Все поды Longhorn в состоянии Running"

    # ======================================================================

    - name: Проверка состояния подов Longhorn
      changed_when: false
      ansible.builtin.shell: |
        kubectl get pods -n longhorn-system
      register: longhorn_pods

    - name: Вывод состояния подов Longhorn
      ansible.builtin.debug:
        var: longhorn_pods.stdout

    # ======================================================================

    - name: Завершение выполнение плэйбука, если не все поды Longhorn в состоянии Running
      ansible.builtin.meta: end_play
      when:
        - count_longhorn_pods_not_running.stdout != target_count