---
# vars file for Longhorn-Taints

target_count:           "0"
taint:                  "key1=value1:NoSchedule"

longhorn_api_version:   "longhorn.io/v1beta2"
longhorn_namespace:     "longhorn-system"
