---

# tasks file for 02-High-Availability

- name: Изменить настройки ядра Linux (net.ipv4.ip_nonlocal_bind)
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    sysctl_set: true
    state: present
    ignoreerrors: true

- name: Создание системного пользователя для HAProxy (для Altlinux)
  when:
    - ansible_os_family == "Altlinux"
  ansible.builtin.user:
    name: haproxy
    system: true
    shell: /usr/sbin/nologin
    home: /nonexistent
    comment: "HAProxy system user"
    state: present

- name: Установка пакетов для Keepalived и HAProxy (не на Altlinux)
  when:
    - ansible_os_family != "Altlinux"
  ansible.builtin.package:
    name:
      - keepalived
      - haproxy
    state: present

- name: Установка пакетов для Keepalived и HAProxy (на Altlinux)
  when:
    - ansible_os_family == "Altlinux"
  community.general.apt_rpm:
    update_cache: true
    pkg:
      - keepalived
      - haproxy
    state: latest

- name: Скопировать keepalived.conf
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify:
    - Restart keepalived

- name: Скопировать haproxy.cfg
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - Restart haproxy
