---

# tasks file for 02-High-Availability

- name: Set sysctl
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    sysctl_set: true
    state: present
    ignoreerrors: true

- name: Install packages RedHat
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "RED"
  ansible.builtin.dnf:
    name:
      - keepalived
      - haproxy
    state: present

- name: Copy keepalived.conf
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify:
    - Restart keepalived

- name: Copy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify:
    - Restart haproxy
