---


# =============================================================================
#             Установка ContainerD на Ubuntu (из репозиториев)
# =============================================================================

- name: Block для "Ubuntu"
  when:
    - ansible_facts.os_family == "Debian"
  become: true
  block:

    - name: Установка containerd для "Ubuntu"
      ansible.builtin.apt:
        update_cache: true
        name:
          - containerd
        state: present
      notify:
        - Start containerd

# =============================================================================
#                          Установка из бинарников
# =============================================================================

- name: Установка containerd (не на Altlinux и не на Ubuntu)
  become: true
  when:
    - ansible_facts.os_family != "Debian"
    - ansible_facts.os_family != "Altlinux"
  block:

    # ======================================================================
    #                    Скачать и распаковать ContainerD
    # ======================================================================

    - name: Загрузить ContainerD "{{ containerd_url }}"
      ansible.builtin.get_url:
        url: "{{ containerd_url }}"
        dest: "{{ kubeadm_temp_folder }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
        owner: root
        group: root
        mode: "0644"
      register: containerd_download_result

    - name: Распаковать архив с ContainerD
      become: true
      ansible.builtin.unarchive:
        src: "{{ kubeadm_temp_folder }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: true

    # ======================================================================
    #                           Containerd Service
    # ======================================================================

    - name: Создание папку /usr/local/lib/systemd/system
      ansible.builtin.file:
        path: /usr/local/lib/systemd/system
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Скопировать containerd.service
      ansible.builtin.get_url:
        url: "{{ containerd_service_url }}"
        dest: /usr/local/lib/systemd/system/containerd.service
        owner: root
        group: root
        mode: "0644"
      notify:
        - Start containerd

    # ======================================================================
    #                        Изменить PATH в .bashrc
    # ======================================================================

    - name: Добавить /usr/local/bin в .bashrc
      become: true
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "{{ item }}"
      with_items:
        - "export PATH=$PATH:/usr/local/bin"

# ======================================================================
#                    Установка ContainerD на Altlinux
# ======================================================================

- name: Установка containerd (на Altlinux)
  become: true
  when:
    - ansible_facts.os_family == "Altlinux"
  block:

    - name: Установка containerd (на Altlinux)
      community.general.apt_rpm:
        update_cache: true
        pkg:
          - "containerd"
          - "cri-tools{{ kubernetes_major_version }}"
        state: latest
      notify:
        - Start containerd

# ======================================================================
#                        Скопировать config.toml
# ======================================================================

- name: Создание папки /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Скопировать config.toml
  become: true
  ansible.builtin.template:
    src: config-{{ containerd_config_version }}.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart containerd

- name: Блок для v3 конфигурации ContainerD
  become: true
  when:
    - containerd_config_version == "v3"
  block:

    - name: Создание папок для репозиториев
      ansible.builtin.file:
        path: "/etc/containerd/certs.d/{{ item.name }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ registries }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Копирование hosts.toml для каждого репозитория
      ansible.builtin.template:
        src: hosts-{{ docker_proxy_registry_type }}.toml.j2
        dest: "/etc/containerd/certs.d/{{ item.name }}/hosts.toml"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ registries }}"
      loop_control:
        label: "{{ item.name }}"
      notify: Restart containerd

# ======================================================================
#                        Скопировать crictl.yaml
# ======================================================================

- name: Скопировать crictl.yaml
  become: true
  ansible.builtin.template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart containerd

# =============================================================================
#                  Добавление CA сертификатов для ContainerD
# =============================================================================

- name: Блок для добавления CA сертификатов для ContainerD, если репозиторий HTTPS
  become: true
  block:

    - name: Создание папки для репозиториев
      ansible.builtin.file:
        path: "{{ containerd_certs_dir }}/{{ item | basename | regex_replace('.crt$', '') }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_fileglob:
        - "files/.certs/*.crt"

    - name: Скопировать сертификаты CA
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ containerd_certs_dir }}/{{ item | basename | regex_replace('.crt$', '') }}/{{ item | basename }}"
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
        - "files/.certs/*.crt"
      notify:
        - Restart containerd
