---
# handlers file for Containerd-config

- name: Restart containerd
  become: true
  ansible.builtin.systemd_service:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
