---
# tasks file for 04-Adding-Other-Nodes

# =============================================================================
#              Получить токены для добавления нод (на 1-й мастер ноде)
# =============================================================================

- name: Блок на получение токенов для добавления нод (на 1-й мастер ноде)
  become: true
  when:
    - inventory_hostname == groups['k8s_masters'][0]
  block:

    # =========================================================================
    #          Получить список всех добавленных нод в кластере
    # =========================================================================

    - name: Получить список всех нод, имеющихся в кластере
      ignore_errors: true
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail
        kubectl get nodes --no-headers | awk '{print $1}'
      register: all_nodes
      args:
        executable: /bin/bash

    - name: Перезаписать переменную "all_nodes"
      ansible.builtin.set_fact:
        all_nodes: "{{ all_nodes.stdout }}"

    - name: Показать переменную "all_nodes"
      ansible.builtin.debug:
        var: all_nodes

    # =========================================================================
    #                           Get join_path
    # =========================================================================

    - name: Получить "join_path"
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail
        kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}' | cut -c9-
      register: join_path
      args:
        executable: /bin/bash

    - name: Перезаписать переменную "join_path"
      ansible.builtin.set_fact:
        join_path: "{{ join_path.stdout }}"

    - name: Показать переменную "join_path"
      ansible.builtin.debug:
        var: join_path

    # =========================================================================
    #                           Get join_token
    # =========================================================================

    - name: Получить "join_token"
      ansible.builtin.shell: |
        set -o pipefail
        kubeadm token create
      register: join_token
      args:
        executable: /bin/bash

    - name: Перезаписать переменную "join_token"
      ansible.builtin.set_fact:
        join_token: "{{ join_token.stdout }}"

    - name: Показать переменную "join_token"
      ansible.builtin.debug:
        var: join_token

    # =========================================================================
    #                          Get ca_cert_hash
    # =========================================================================

    - name: Получить "ca_cert_hash"
      ansible.builtin.shell: |
        set -o pipefail
        openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
        openssl rsa -pubin -outform der 2>/dev/null | \
        openssl dgst -sha256 -hex | sed 's/^.* //'
      register: ca_cert_hash
      args:
        executable: /bin/bash

    - name: Перезаписать переменную "ca_cert_hash"
      ansible.builtin.set_fact:
        ca_cert_hash: "{{ ca_cert_hash.stdout }}"

    - name: Показать переменную "ca_cert_hash"
      ansible.builtin.debug:
        var: ca_cert_hash

    # =========================================================================
    #                          Get Get certificate_key
    # =========================================================================

    - name: Получить "certificate_key"
      ansible.builtin.shell: |
        set -o pipefail
        kubeadm init phase upload-certs --upload-certs | tail -1
      register: certificate_key
      args:
        executable: /bin/bash

    - name: Перезаписать переменную "certificate_key"
      ansible.builtin.set_fact:
        certificate_key: "{{ certificate_key.stdout }}"

    - name: Показать переменную "certificate_key"
      ansible.builtin.debug:
        var: certificate_key


# =============================================================================
#                              Блок добавления нод
# =============================================================================


- name: Блок на добавление нод, если они еще не добавлены в кластер
  become: true
  when:
    - inventory_hostname not in hostvars[groups['k8s_masters'][0]].all_nodes
  block:

    # =========================================================================
    #                              Блок добавления master-нод
    # =========================================================================

    - name: Блок на добавление мастер-нод
      become: true
      when:
        - inventory_hostname in groups['k8s_masters'][1:]
      block:

        - name: Добавление мастер-ноды {{ inventory_hostname }}
          ansible.builtin.shell:
            cmd: |
              kubeadm join {{ hostvars[groups['k8s_masters'][0]].join_path }} \
              --token {{ hostvars[groups['k8s_masters'][0]].join_token }} \
              --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].ca_cert_hash }} \
              --certificate-key {{ hostvars[groups['k8s_masters'][0]].certificate_key }} \
              --node-name {{ inventory_hostname }} \
              --control-plane
          args:
            executable: /bin/bash

        - name: Создание папки /root/.kube
          ansible.builtin.file:
            path: /root/.kube
            state: directory
            owner: root
            group: root
            mode: "0775"

        - name: Скопировать /etc/kubernetes/admin.conf в /root/.kube/config
          become: true
          ansible.builtin.copy:
            src: /etc/kubernetes/admin.conf
            dest: /root/.kube/config
            remote_src: true
            owner: root
            group: root
            mode: "0600"

        - name: Pause for 30 seconds
          ansible.builtin.pause:
            seconds: 30

    # =========================================================================
    #                         Блок добавления worker-нод
    # =========================================================================

    - name: Блок на добавление worker-нод
      become: true
      when:
        - inventory_hostname in groups['k8s_workers']
      block:

        - name: Добавление worker-ноды {{ inventory_hostname }}
          ansible.builtin.shell:
            cmd: |
              kubeadm join {{ hostvars[groups['k8s_masters'][0]].join_path }} \
              --token {{ hostvars[groups['k8s_masters'][0]].join_token }} \
              --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].ca_cert_hash }} \
              --node-name {{ inventory_hostname }}
          args:
            executable: /bin/bash
