---

# ======================================= CNI Driver (Calico) ======================================

- name: Install pip for RedHat
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "RED"
  become: true
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install pip for Ubuntu
  when:
    - ansible_os_family == "Ubuntu"
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install pre-requisites for kubernetes.core.k8s
  ansible.builtin.pip:
    name:
      - pyyaml
      - kubernetes
      - jsonpatch

- name: Download Tigera Calico operator
  ansible.builtin.get_url:
    url: "{{ calico_operator_link }}"
    dest: ~/download/tigera-operator.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Tigera Calico operator
  kubernetes.core.k8s:
    src: ~/download/tigera-operator.yaml
    state: present

- name: Copy calico-install.yaml
  become: true
  ansible.builtin.template:
    src: calico-install.yaml.j2
    dest: ~/kubeadm/calico-install.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Calico
  kubernetes.core.k8s:
    src: ~/kubeadm/calico-install.yaml
    state: present
  notify:
    - Restart kubelet
