---

# ======================================= CNI Driver (Calico) ======================================

- name: Download Tigera Calico operator
  ansible.builtin.get_url:
    url: "{{ calico_operator_link }}"
    dest: ~/download/tigera-operator.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Tigera Calico operator
  kubernetes.core.k8s:
    src: ~/download/tigera-operator.yaml
    state: present

- name: Copy calico-install.yaml
  become: true
  ansible.builtin.template:
    src: calico-install.yaml.j2
    dest: ~/kubeadm/calico-install.yaml
    owner: root
    group: root
    mode: "0644"

- name: Apply Calico
  kubernetes.core.k8s:
    src: ~/kubeadm/calico-install.yaml
    state: present
  notify:
    - Restart kubelet
