---

# =============================================================================
#                            Установка Runc на Ubuntu
# =============================================================================

- name: Block для "Ubuntu"
  when:
    - ansible_facts.os_family == "Debian"
  become: true
  block:

    - name: Установка Runc для "Ubuntu"
      ansible.builtin.apt:
        update_cache: true
        name:
          - runc
        state: present

# =============================================================================
#                         Установка Runc из бинарников
# =============================================================================

- name: Установка Runc из бинарников
  become: true
  when:
    - ansible_facts.os_family != "Debian"
    - ansible_facts.os_family != "Altlinux"
  block:

    - name: Загрузить Runc
      ansible.builtin.get_url:
        url: "{{ runc_url }}"
        dest: "{{ kubeadm_temp_folder }}/runc.amd64"
        owner: root
        group: root
        mode: "0644"

    - name: Установить Runc
      become: true
      ansible.builtin.copy:
        src: "{{ kubeadm_temp_folder }}/runc.amd64"
        dest: /usr/local/sbin/runc
        remote_src: true
        owner: root
        group: root
        mode: "0755"

# =============================================================================
#                                   Altlinux
# =============================================================================

- name: Установка Runc на Altlinux
  become: true
  when:
    - ansible_facts.os_family == "Altlinux"
  block:

    - name: Установка Runc (на Altlinux)
      community.general.apt_rpm:
        update_cache: true
        pkg:
          - "runc"
        state: latest
