---
# tasks file for Install-Metrics-Server

- name: Создание папку download
  ansible.builtin.file:
    path: '/root/download'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download manifest
  ansible.builtin.get_url:
    url: "{{ manistst_link }}"
    dest: "/root/download/{{ manifest_name }}"
    owner: root
    group: root
    mode: "0644"

# ======================================= Install Metrics Server =======================================

- name: Apply Metrics Server
  kubernetes.core.k8s:
    src: "/root/download/{{ manifest_name }}"
    state: present

- name: Подписать все сертификаты
  ansible.builtin.shell: |
    if kubectl get csr --sort-by=.metadata.creationTimestamp --no-headers --output=jsonpath='{.items[0].metadata.name}'; then
      kubectl get csr --sort-by=.metadata.creationTimestamp --no-headers | awk '{print $1}' | xargs kubectl certificate approve
    fi
