---

# =============================================================================
#                                  Установка Ubuntu
# =============================================================================

- name: Установка CRI-O (на Ubuntu)
  become: true
  when:
    - ansible_facts.os_family == "Debian"
  block:

    - name: Установка cri-o для "Ubuntu"
      ansible.builtin.apt:
        update_cache: true
        name:
          - cri-o
        state: present
      notify:
        - Start crio

    - name: Скопировать nexus.conf
      become: true
      when:
        - docker_proxy_registry_type == "nexus"
      ansible.builtin.template:
        src: nexus.conf.j2
        dest: /etc/containers/registries.conf.d/crio.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart crio

    - name: Скопировать harbor.conf
      become: true
      when:
        - docker_proxy_registry_type == "harbor"
      ansible.builtin.template:
        src: harbor.conf.j2
        dest: /etc/containers/registries.conf.d/crio.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart crio

# =============================================================================
#                             Установка на Altlinux
# =============================================================================

- name: Установка CRI-O (на Altlinux)
  become: true
  when:
    - ansible_facts.os_family == "Altlinux"
  block:

    - name: Установка CRI-O (на Altlinux)
      community.general.apt_rpm:
        update_cache: true
        pkg:
          - "kubernetes{{ kubernetes_major_version }}-crio"
          - "cri-tools{{ kubernetes_major_version }}"
        state: latest
      notify:
        - Start crio

    - name: Убрать лишние репозитории из registries.conf
      ansible.builtin.replace:
        path: /etc/containers/registries.conf
        regexp: '^unqualified-search-registries = \[.*\]$'
        replace: 'unqualified-search-registries = ["registry.altlinux.org"]'

    - name: Скопировать nexus.conf
      become: true
      when:
        - docker_proxy_registry_type == "nexus"
      ansible.builtin.template:
        src: nexus.conf.j2
        dest: /etc/containers/registries.conf.d/nexus.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart crio

    - name: Скопировать harbor.conf
      become: true
      when:
        - docker_proxy_registry_type == "harbor"
      ansible.builtin.template:
        src: harbor.conf.j2
        dest: /etc/containers/registries.conf.d/harbor.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart crio
