# ==============================================================================
#                                SSH Settings
# ==============================================================================

ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: auto_silent

# ==============================================================================
#                                  Image Repository
# ==============================================================================

# # Docker Proxy Registry Type
docker_proxy_registry_type: "nexus"
# docker_proxy_registry_type: "harbor"

# ==============================================================================
#                                Install ContainerD
# ==============================================================================

install_containerd: true
# containerd_version: "2.3.0"
# containerd_config_version: "v2"
containerd_config_version: "v3"

# ==============================================================================
#                                Install NerdCTL
# ==============================================================================

install_nerdctl: true
nerdctl_version: "2.2.2"

# ==============================================================================
#                                Install CRI-O
# ==============================================================================

install_crio: false

# # Kubernetes Version
# kubernetes_major_version: "1.35"
# kubernetes_minor_version: "1.35.3"

# ==============================================================================
#                                  Install Runc
# ==============================================================================

install_runc: true
# runc_version: "1.4.2"

# ==============================================================================
#                               Install CNI Plugins
# ==============================================================================

install_cni_plugins: true
# cni_plugins_version: "1.9.1"

# ==============================================================================
#                                  Install Helm
# ==============================================================================

install_helm: true
helm_version: "4.1.1"

# ==============================================================================
#                                  Install K9s
# ==============================================================================

install_k9s: true
k9s_version: "0.50.18"

# ==============================================================================
#                          Install Packages for Longhorn
# ==============================================================================

install_packages_for_longhorn: true
