---
# tasks file for user

# ============================================== Ping ==============================================

- name: Ping
  become: true
  ansible.builtin.ping:

- name: Create user "{{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"
    groups: wheel
    password: "{{ upassword | string | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
    create_home: true

- name: Скопировать файл "{{ username }}" в папку "/etc/sudoers.d/"
  ansible.builtin.template:
    src: user_template.j2
    dest: "/etc/sudoers.d/{{ username }}"
    owner: root
    group: root
    mode: "0400"
