---
# tasks file for 06-Delete-Control-Node

# =============================================================================
#              Получить токены для добавления нод (на 1-й мастер ноде)
# =============================================================================

- name: Блок на получение всех нод в кластере
  become: true
  run_once: true
  when:
    - inventory_hostname in groups['k8s_masters']
  block:

    # =========================================================================
    #          Получить список всех добавленных нод в кластере
    # =========================================================================

    - name: Получить список всех нод в кластере
      ignore_errors: true
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail
        kubectl get nodes --no-headers | awk '{print $1}'
      register: all_nodes
      args:
        executable: /bin/bash

    # - name: Create variable all_nodes
    #   ansible.builtin.set_fact:
    #     all_nodes: "{{ all_nodes.stdout }}"

    # - name: Вывод списка всех нод в кластере
    #   ansible.builtin.debug:
    #     var: all_nodes.stdout_lines

    - name: Получить списов всех мастер-нод в кластере
      ignore_errors: true
      changed_when: false
      ansible.builtin.shell: |
        set -o pipefail
        kubectl get nodes --no-headers | grep control-plane | awk '{print $1}'
      register: all_cpl_nodes
      args:
        executable: /bin/bash

    - name: Перезаписать переменную all_cpl_nodes
      ansible.builtin.set_fact:
        all_cpl_nodes: "{{ all_cpl_nodes.stdout }}"

    - name: Цикл по всем нодам в кластере
      ansible.builtin.include_tasks: delete_node_loop.yaml
      loop: "{{ all_nodes.stdout_lines }}"
      loop_control:
        label: "{{ item }}"
