---

# =============================================================================
#                      Добавление CA сертификатов для Harbor
# =============================================================================

- name: Сбор фактов о имеющихся сервисах
  ansible.builtin.service_facts:

- name: Установить CA сертификат (Block для "RedHat")
  when:
    - ansible_facts.os_family == "RedHat" or ansible_facts.os_family == "RED"
  become: true
  block:

    - name: Скопировать сертификат CA (RedHat)
      become: true
      ansible.builtin.copy:
        src: .certs/ca.crt
        dest: "{{ ca_certificate_redhat_path }}/harbor-ca.crt"
        owner: root
        group: root
        mode: "0644"
      notify:
        - Run update-ca-trust RedHat
        - Restart containerd

- name: Block для containerd
  become: true
  block:

    - name: Установка containerd (не на Altlinux)
      become: true
      when:
        - ansible_facts.os_family != "Altlinux"
      block:

        # ======================================================================
        #                         Harbor Docker Registry
        # ======================================================================

        - name: Создание папки для репозиториев "{{ containerd_certs_dir }}"
          ansible.builtin.file:
            path: "{{ containerd_certs_dir }}/{{ harbor_repository_url }}"
            state: directory
            owner: root
            group: root
            mode: '0755'

        - name: Скопировать сертификат CA
          become: true
          ansible.builtin.copy:
            src: .certs/ca.crt
            dest: "{{ harbor_repository_ca_file }}"
            owner: root
            group: root
            mode: "0644"
          notify:
            - Restart containerd

        # # Не работает пока (для Containerd config_path)
        # - name: Создание папок для репозиториев
        #   ansible.builtin.file:
        #     path: "{{ containerd_certs_dir }}/{{ item.name }}"
        #     state: directory
        #     owner: root
        #     group: root
        #     mode: '0755'
        #   loop: "{{ registries }}"

        # # Не работает пока (для Containerd config_path)
        # - name: Скопировать hosts.toml для репозиториев
        #   become: true
        #   ansible.builtin.template:
        #     src: hosts.toml.j2
        #     dest: "{{ containerd_certs_dir }}/{{ item.name }}/hosts.toml"
        #     owner: root
        #     group: root
        #     mode: "0644"
        #   loop: "{{ registries }}"
        #   notify:
        #     - Restart containerd